name: Push-OSS

on: [push]
jobs:
  test:
    # I promise I'll add tests later
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Build Kalasearch Douban Demo Site
      run: |
        yarn install
        yarn build
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-beijing.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deply To OSS
      run: ossutil cp public oss://kalasearch-douban-movies-demo/ -rf
